export const MALAYSIA_STATES = [
  { value: "johor", label: "Johor" },
  { value: "kedah", label: "Kedah" },
  { value: "kelantan", label: "Kelantan" },
  { value: "kuala_lumpur", label: "Kuala Lumpur" },
  { value: "labuan", label: "Labuan" },
  { value: "malacca", label: "Malacca" },
  { value: "negeri_sembilan", label: "Negeri Sembilan" },
  { value: "pahang", label: "Pahang" },
  { value: "penang", label: "Penang" },
  { value: "perak", label: "Perak" },
  { value: "perlis", label: "Perlis" },
  { value: "putrajaya", label: "Putrajaya" },
  { value: "sabah", label: "Sabah" },
  { value: "sarawak", label: "Sarawak" },
  { value: "selangor", label: "Selangor" },
  { value: "terengganu", label: "Terengganu" },
] as const;

export const MALAYSIA_CITIES: Record<string, string[]> = {
  johor: ["Johor Bahru", "Muar", "Batu Pahat", "Kluang", "Segamat", "Kulai"],
  kedah: ["Alor Setar", "Sungai Petani", "Kulim", "Langkawi", "Jitra"],
  kelantan: ["Kota Bharu", "Tanah Merah", "Pasir Mas", "Gua Musang"],
  kuala_lumpur: ["Kuala Lumpur"],
  labuan: ["Victoria"],
  malacca: ["Malacca City", "Alor Gajah", "Jasin"],
  negeri_sembilan: ["Seremban", "Port Dickson", "Nilai", "Bahau"],
  pahang: ["Kuantan", "Temerloh", "Bentong", "Raub", "Jerantut"],
  penang: ["George Town", "Butterworth", "Bukit Mertajam", "Nibong Tebal"],
  perak: ["Ipoh", "Taiping", "Teluk Intan", "Sitiawan", "Kuala Kangsar"],
  perlis: ["Kangar", "Arau"],
  putrajaya: ["Putrajaya"],
  sabah: ["Kota Kinabalu", "Sandakan", "Tawau", "Lahad Datu", "Keningau"],
  sarawak: ["Kuching", "Miri", "Sibu", "Bintulu", "Limbang"],
  selangor: [
    "Shah Alam",
    "Petaling Jaya",
    "Subang Jaya",
    "Klang",
    "Ampang",
    "Kajang",
    "Selayang",
    "Sepang",
  ],
  terengganu: ["Kuala Terengganu", "Kemaman", "Dungun", "Marang"],
};
